"""Adds payout type column

Revision ID: 3460331ee9a9
Revises: None
Create Date: 2014-04-16 16:52:40.861334

"""

# revision identifiers, used by Alembic.
revision = '3460331ee9a9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('payout_type', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'payout_type')
    ### end Alembic commands ###
