"""REMOVE: Last update column added to table

Revision ID: 435ef072f367
Revises: 4954f426ac31
Create Date: 2014-04-16 19:37:40.919186

"""

# revision identifiers, used by Alembic.
revision = '435ef072f367'
down_revision = '4954f426ac31'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'last_checkin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('last_checkin', postgresql.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###
