"""Last update column added to table

Revision ID: 4954f426ac31
Revises: 28bccdac7001
Create Date: 2014-04-16 17:35:19.167175

"""

# revision identifiers, used by Alembic.
revision = '4954f426ac31'
down_revision = '28bccdac7001'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('last_checkin', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'last_checkin')
    ### end Alembic commands ###
